name: bemixtral
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - accelerate==0.25.0
    - aiohttp==3.9.1
    - aiosignal==1.3.1
    - annotated-types==0.6.0
    - anyio==3.7.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - auto-gptq==0.6.0
    - certifi==2023.11.17
    - charset-normalizer==3.3.2
    - click==8.1.7
    - coloredlogs==15.0.1
    - datasets==2.15.0
    - dill==0.3.7
    - einops==0.7.0
    - exceptiongroup==1.2.0
    - fastapi==0.105.0
    - filelock==3.13.1
    - flash-attn==2.3.6
    - frozenlist==1.4.1
    - fsspec==2023.10.0
    - gekko==1.0.6
    - h11==0.14.0
    - huggingface-hub==0.19.4
    - humanfriendly==10.0
    - idna==3.6
    - jinja2==3.1.2
    - markupsafe==2.1.3
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.15
    - networkx==3.2.1
    - ninja==1.11.1.1
    - numpy==1.26.2
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.101
    - nvidia-nvtx-cu12==12.1.105
    - optimum==1.16.1
    - packaging==23.2
    - pandas==2.1.4
    - peft==0.7.1
    - protobuf==4.25.1
    - psutil==5.9.6
    - pyarrow==14.0.1
    - pyarrow-hotfix==0.6
    - pydantic==2.5.2
    - pydantic-core==2.14.5
    - python-dateutil==2.8.2
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - regex==2023.10.3
    - requests==2.31.0
    - rouge==1.0.1
    - safetensors==0.4.1
    - sentencepiece==0.1.99
    - six==1.16.0
    - sniffio==1.3.0
    - sseclient==0.0.27
    - starlette==0.27.0
    - sympy==1.12
    - tiktoken==0.5.2
    - tokenizers==0.15.0
    - torch==2.1.2
    - tqdm==4.66.1
    - transformers==4.37.0.dev0
    - triton==2.1.0
    - typing-extensions==4.9.0
    - tzdata==2023.3
    - urllib3==2.1.0
    - uvicorn==0.24.0.post1
    - xxhash==3.4.1
    - yarl==1.9.4
prefix: /home/ed/anaconda3/envs/bemixtral
